# src/Blogger/CoreBundle/Resources/config/routing.yml
DevCoreBundle_homepage:
    pattern:  /
    defaults: { _controller: DevCoreBundle:Page:index }
    requirements:
        _method:  GET|POST

DevCoreBundle_about:
    pattern:  /about
    defaults: { _controller: DevCoreBundle:Page:about }
    requirements:
        _method:  GET

DevCoreBundle_blog_show:
    pattern:  /blog/show/{id}
    defaults: { _controller: DevCoreBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

