# src/Blogger/BlogBundle/Resources/config/routing.yml
DevCoreBundle_homepage:
    pattern:  /
    defaults: { _controller: DevCoreBundle:Page:index }
    requirements:
        _method:  GET

DevCoreBundle_about:
    pattern:  /about
    defaults: { _controller: DevCoreBundle:Page:about }
    requirements:
        _method:  GET

